M48
; DRILL file {KiCad 7.0.10} date Tue Aug 26 16:00:30 2025
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-26T16:00:30+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X82.6Y-22.5
X85.6Y-22.5
X107.6Y-44.2
X107.6Y-47.2
T2
X22.8Y-97.6
X27.8Y-35.6
X31.8Y-106.6
X56.8Y-22.6
X93.8Y-101.6
X94.8Y-22.6
X106.8Y-34.6
X106.8Y-72.6
M30
